---
title: "generate_plot_0827"
output: html_document
date: "2024-08-27"
---
```{r}
library(ggplot2)
library(readxl)
library(patchwork)
```

```{r}
## Simulation_similarity_index

df_si <- read_excel("/Volumes/Newsmy 1/phd/cepstral_distance/code/matlab/Simulation/K-medoids_eu_similarity_index.xlsx")

# Replace with your actual method names
method_order <- c("log-Periodogram", "rect", "hann", "BIC", "KSF", "MRI", "FDR_0.01", "FER_0.01", "FDR_0.05", "FER_0.05")
  
# Create the first plot for Weight == "Identity"
df_identity <- subset(df_si, Weight == "Identity")

p1 <- ggplot(df_identity, aes(x = as.factor(N), y = sim_metrics, color = factor(Method, levels = method_order), group = factor(Method, levels = method_order))) +
  geom_line(linewidth = 1.2) +  # Draw the line plot
  geom_point(size = 3) +    # Add data points
  labs(title = "Identity Matrix", x = "Sample Size", y = "Similarity Index (mean)", color = "N") + scale_color_discrete(
    labels = c(
      "log-Periodogram" = "log-Periodogram",
      "hann" = "Hann",
      "rect" = "periodogram",
      "BIC" = "BIC",
      "KSF" = "KSF",
      "MRI" = "MRI",
      "FDR_0.01" = expression(FDR[alpha == 0.01]),
      "FER_0.01" = expression(FER[alpha == 0.01]),
      "FDR_0.05" = expression(FDR[alpha == 0.05]),
      "FER_0.05" = expression(FER[alpha == 0.05])
    )) +
  theme_bw() +
  theme(legend.position = "none", 
        axis.title.y = element_text(size = 11), 
        plot.title = element_text(size = 12, hjust = 0.5), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.text.x = element_text(size = 11, angle = 30,vjust = 0.85,hjust = 0.75), 
        legend.text = element_text(size = 10), 
        legend.title = element_text(size = 11))

# Display the first plot
print(p1)

# Create the second plot for Weight == "Martin"
df_martin <- subset(df_si, Weight == "Martin")

p2 <- ggplot(df_martin, aes(x = as.factor(N), y = sim_metrics, color = factor(Method, levels = method_order), group = factor(Method, levels = method_order))) +
  geom_line(linewidth = 1.2) +  # Draw the line plot
  geom_point(size = 3) +    # Add data points
  labs(title = "Martin Matrix", x = "Sample Size", y = "Similarity Index (mean)", color = "Method")+ scale_color_discrete(
    labels = c(
      "log-Periodogram" = "log-Periodogram",
      "hann" = "Hann",
      "rect" = "periodogram",
      "BIC" = "BIC",
      "KSF" = "KSF",
      "MRI" = "MRI",
      "FDR_0.01" = expression(FDR[alpha == 0.01]),
      "FER_0.01" = expression(FER[alpha == 0.01]),
      "FDR_0.05" = expression(FDR[alpha == 0.05]),
      "FER_0.05" = expression(FER[alpha == 0.05])
    )) + 
  theme_bw() +
  theme(axis.title.y = element_text(size = 11), 
        plot.title = element_text(size = 12, hjust = 0.5), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.text.x = element_text(size = 11, angle = 30,vjust = 0.85,hjust = 0.75), 
        legend.text = element_text(size = 10), 
        legend.title = element_text(size = 11))

# Display the second plot
print(p2)

p3 <- p1 + p2

setwd("/Volumes/Newsmy 1/phd/cepstral_distance/results/graph")
pdf("figure3_k-mediods_eu.pdf", width = 9, height = 6)
p3

dev.off()
```

```{r}
## Simulation_similarity_index

df_si <- read_excel("/Volumes/Newsmy 1/phd/cepstral_distance/code/matlab/Simulation/K-means_similarity_index.xlsx")

# Replace with your actual method names
method_order <- c("log-Periodogram", "rect", "hann", "BIC", "KSF", "MRI", "FDR_0.01", "FER_0.01", "FDR_0.05", "FER_0.05")
  
# Create the first plot for Weight == "Identity"
df_identity <- subset(df_si, Weight == "Identity")

p4 <- ggplot(df_identity, aes(x = as.factor(N), y = sim_metrics, color = factor(Method, levels = method_order), group = factor(Method, levels = method_order))) +
  geom_line(linewidth = 1.2) +  # Draw the line plot
  geom_point(size = 3) +    # Add data points
  labs(title = "Identity Matrix", x = "Sample Size", y = "Similarity Index (mean)", color = "N") + scale_color_discrete(
    labels = c(
      "log-Periodogram" = "log-Periodogram",
      "hann" = "Hann",
      "rect" = "periodogram",
      "BIC" = "BIC",
      "KSF" = "KSF",
      "MRI" = "MRI",
      "FDR_0.01" = expression(FDR[alpha == 0.01]),
      "FER_0.01" = expression(FER[alpha == 0.01]),
      "FDR_0.05" = expression(FDR[alpha == 0.05]),
      "FER_0.05" = expression(FER[alpha == 0.05])
    )) +
  theme_bw() +
  theme(legend.position = "none", 
        axis.title.y = element_text(size = 11), 
        plot.title = element_text(size = 12, hjust = 0.5), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.text.x = element_text(size = 11, angle = 30,vjust = 0.85,hjust = 0.75), 
        legend.text = element_text(size = 10), 
        legend.title = element_text(size = 11))

# Display the first plot
print(p4)

# Create the second plot for Weight == "Martin"
df_martin <- subset(df_si, Weight == "Martin")

p5 <- ggplot(df_martin, aes(x = as.factor(N), y = sim_metrics, color = factor(Method, levels = method_order), group = factor(Method, levels = method_order))) +
  geom_line(linewidth = 1.2) +  # Draw the line plot
  geom_point(size = 3) +    # Add data points
  labs(title = "Martin Matrix", x = "Sample Size", y = "Similarity Index (mean)", color = "Method")+ scale_color_discrete(
    labels = c(
      "log-Periodogram" = "log-Periodogram",
      "hann" = "Hann",
      "rect" = "periodogram",
      "BIC" = "BIC",
      "KSF" = "KSF",
      "MRI" = "MRI",
      "FDR_0.01" = expression(FDR[alpha == 0.01]),
      "FER_0.01" = expression(FER[alpha == 0.01]),
      "FDR_0.05" = expression(FDR[alpha == 0.05]),
      "FER_0.05" = expression(FER[alpha == 0.05])
    )) + 
  theme_bw() +
  theme(axis.title.y = element_text(size = 11), 
        plot.title = element_text(size = 12, hjust = 0.5), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.text.x = element_text(size = 11, angle = 30,vjust = 0.85,hjust = 0.75), 
        legend.text = element_text(size = 10), 
        legend.title = element_text(size = 11))

# Display the second plot
print(p5)

p6 <- p4 + p5

setwd("/Volumes/Newsmy 1/phd/cepstral_distance/results/graph")
pdf("figure3_k-means.pdf", width = 9, height = 6)
p6

dev.off()
```

```{r}
## Simulation_similarity_index

df_si <- read_excel("/Volumes/Newsmy 1/phd/cepstral_distance/code/matlab/Simulation/K-medoids_sq_similarity_index.xlsx")

# Replace with your actual method names
method_order <- c("log-Periodogram", "rect", "hann", "BIC", "KSF", "MRI", "FDR_0.01", "FER_0.01", "FDR_0.05", "FER_0.05")
  
# Create the first plot for Weight == "Identity"
df_identity <- subset(df_si, Weight == "Identity")

p7 <- ggplot(df_identity, aes(x = as.factor(N), y = sim_metrics, color = factor(Method, levels = method_order), group = factor(Method, levels = method_order))) +
  geom_line(linewidth = 1.2) +  # Draw the line plot
  geom_point(size = 3) +    # Add data points
  labs(title = "Identity Matrix", x = "Sample Size", y = "Similarity Index (mean)", color = "N") + scale_color_discrete(
    labels = c(
      "log-Periodogram" = "log-Periodogram",
      "hann" = "Hann",
      "rect" = "periodogram",
      "BIC" = "BIC",
      "KSF" = "KSF",
      "MRI" = "MRI",
      "FDR_0.01" = expression(FDR[alpha == 0.01]),
      "FER_0.01" = expression(FER[alpha == 0.01]),
      "FDR_0.05" = expression(FDR[alpha == 0.05]),
      "FER_0.05" = expression(FER[alpha == 0.05])
    )) +
  theme_bw() +
  theme(legend.position = "none", 
        axis.title.y = element_text(size = 11), 
        plot.title = element_text(size = 12, hjust = 0.5), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.text.x = element_text(size = 11, angle = 30,vjust = 0.85,hjust = 0.75), 
        legend.text = element_text(size = 10), 
        legend.title = element_text(size = 11))

# Display the first plot
print(p7)

# Create the second plot for Weight == "Martin"
df_martin <- subset(df_si, Weight == "Martin")

p8 <- ggplot(df_martin, aes(x = as.factor(N), y = sim_metrics, color = factor(Method, levels = method_order), group = factor(Method, levels = method_order))) +
  geom_line(linewidth = 1.2) +  # Draw the line plot
  geom_point(size = 3) +    # Add data points
  labs(title = "Martin Matrix", x = "Sample Size", y = "Similarity Index (mean)", color = "Method")+ scale_color_discrete(
    labels = c(
      "log-Periodogram" = "log-Periodogram",
      "hann" = "Hann",
      "rect" = "periodogram",
      "BIC" = "BIC",
      "KSF" = "KSF",
      "MRI" = "MRI",
      "FDR_0.01" = expression(FDR[alpha == 0.01]),
      "FER_0.01" = expression(FER[alpha == 0.01]),
      "FDR_0.05" = expression(FDR[alpha == 0.05]),
      "FER_0.05" = expression(FER[alpha == 0.05])
    )) + 
  theme_bw() +
  theme(axis.title.y = element_text(size = 11), 
        plot.title = element_text(size = 12, hjust = 0.5), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.text.x = element_text(size = 11, angle = 30,vjust = 0.85,hjust = 0.75), 
        legend.text = element_text(size = 10), 
        legend.title = element_text(size = 11))

# Display the second plot
print(p8)

p9 <- p7 + p8

setwd("/Volumes/Newsmy 1/phd/cepstral_distance/results/graph")
pdf("figure3_k-mediods_sq.pdf", width = 9, height = 6)
p9

dev.off()
```
```

